# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Basic Concepts of Fixed Income:Measuring Interest Rate Risk With Duration"
author: 'Financial Python'
copyright: "2025 by Arbitrage Partners." # This will appear in the footer
logo: 


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PatrickJHess/Vol-3-Chap-7  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  extra_footer: |
    <script>
    document.addEventListener("DOMContentLoaded", function() {
      const currentRepo = window.location.pathname.split('/')[1];

      document.querySelectorAll('a').forEach(link => {
        // Only process links that have a hostname (skips mailto:, etc.)
        if (link.hostname) {
          const linkRepo = link.pathname.split('/')[1];

          // NEW TAB IF: 
          // 1. Different Domain (e.g., google.com)
          // OR 
          // 2. Same Domain but different Repo folder
          if (link.hostname !== window.location.hostname || (linkRepo && linkRepo !== currentRepo)) {
            link.target = '_blank';
            link.rel = 'noopener noreferrer';
          }
        }
      });
    });
    </script>
launch_buttons:
  thebe: true
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
